config/routes.rb
Rails.application.routes.draw do
  resources :wells_fargo_srp_sheets
  resources :wells_fargo_price_sheets
  devise_for :users

  resources :excel_files do
    get 'process_file'
    get 'total_pipeline'
    get 'fnma_type'
    get 'gnma_type'
    get 'non_conforming_type'
  end

  root 'welcome#index'

end

app/models/excel_file.rb
class ExcelFile < ActiveRecord::Base
  attr_accessor :name, :xl
  mount_uploader :xl, XlUploader
  #serialize :json

  def filename
    @xl.split('/').last unless @xl.nil?
  end

end

app/controllers/excel_files_controller.rb
class ExcelFilesController < ApplicationController
  before_action :set_excel_file, only: [:show, :edit, :update, :destroy, :process_file]


  # GET /excel_files
  # GET /excel_files.json
  def index
    @excel_files = ExcelFile.all
  end

  # GET /excel_files/1
  # GET /excel_files/1.json
  def show
  end

  # GET /excel_files/new
  def new
    @excel_file = ExcelFile.new
  end

  # GET /excel_files/1/edit
  def edit
  end

  # POST /excel_files
  # POST /excel_files.json
  def create
    @excel_file = ExcelFile.new(excel_file_params)

    respond_to do |format|
      if @excel_file.save
        format.html { redirect_to @excel_file, notice: 'Excel file was successfully created.' }
        format.json { render :show, status: :created, location: @excel_file }
      else
        format.html { render :new }
        format.json { render json: @excel_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excel_files/1
  # PATCH/PUT /excel_files/1.json
  def update
    respond_to do |format|
      puts 'in ExcelFile update'
      puts "params:#{excel_file_params}"
      if @excel_file.update(excel_file_params)
        format.html { redirect_to @excel_file, notice: 'Excel file was successfully updated.' }
        format.json { render :show, status: :ok, location: @excel_file }
      else
        @excel_file.update_attribute('name', excel_file_params['name'])
        format.html { render :edit }
        format.json { render json: @excel_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excel_files/1
  # DELETE /excel_files/1.json
  def destroy
    @excel_file.destroy
    respond_to do |format|
      format.html { redirect_to excel_files_url, notice: 'Excel file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def process_file
    if @excel_file &&
        @excel_file.xl &&
        @excel_file.xl.file &&
        @excel_file.xl.file.file
      begin
      file = File.new( @excel_file.xl.file.file )
      Rails.logger.info("Processing file:#{file.inspect}")
      if file && file.size > 2000
        loader = MMA::Excel::LoadExcel.new( @excel_file.xl.file.file )
        row_arr = loader.row_arr
        #puts 'row_arr'
        #puts row_arr
      else
        row_arr = []
      end
      rescue Exception => ex
        Rails.logger.warn("Exception when trying to use file:#{ex.message}")
        row_arr = []
      end
    else
      Rails.logger.warn( 'no file found, will process with empty array')
      row_arr = []
    end
    MMA::Excel::ParseExcel.process_array( row_arr )
  end

  def landing
    @excel_file
    redirect_to '/landing_page'
  end

  def fnma_type
    puts 'about to process fnma type loans'
    if MMA::Loan.count > 0
      if WellsFargoPriceSheet.order(:created_at).last
        puts 'found the latest WellsFargoPriceSheet object, not to retrieve the json column...'
        @wf_price_h     = WellsFargoPriceSheet.order(:created_at).last.json[:pricing]
        @wf_adjusters_h = WellsFargoPriceSheet.order(:created_at).last.json[:adjusters]
      else
        @wf_price_h     = WellsFargoPriceSheet.const_json
        @wf_adjusters_h = nil
      end

      if WellsFargoSrpSheet.order(:created_at).last
        @wf_srp_h     = WellsFargoSrpSheet.order(:created_at).last.json
      else
        @wf_srp_h     = nil
      end

      rate_obj= MMA::Banks::Utils::RateMatcher.new( @wf_price_h, @wf_adjusters_h, @wf_srp_h )

      @fnma_15_loans= MMA::Loan.where("loan_program IN ('#{MMA::FNMA_15_TYPE_ARRAY.join("','")}')").order(:loan_program)
      @fnma_15_opn  = @fnma_15_loans.select{|loan| ! loan.is_closed }
      @f_15_opn_h   = MMA::Banks::WellsFargo::RegularAdjusters::Adjusters.loan_hash_from_subset( @fnma_15_opn )
      @f_15_opn_h.each do |k,l_h|
        l_h = l_h.stringify_keys
        price_h = rate_obj.find_rate_price( l_h )
        adj_h   = rate_obj.find_price_adjusters( l_h )
        srp_h   = rate_obj.find_srp_adjusters( l_h )
        l_h[:wf_price]  = price_h
        l_h[:wf_adj]    = adj_h
        l_h[:wf_srp]    = srp_h
        #puts "f_15_open:#{l_h}"
        @f_15_opn_h[k] = l_h
      end
      @fnma_15_clsd = @fnma_15_loans.select{|loan| loan.is_closed }
      @f_15_clsd_h  = MMA::Banks::WellsFargo::RegularAdjusters::Adjusters.loan_hash_from_subset( @fnma_15_clsd )
      @f_15_clsd_h.each do |k,l_h|
        l_h = l_h.stringify_keys
        price_h = rate_obj.find_rate_price( l_h )
        adj_h   = rate_obj.find_price_adjusters( l_h )
        srp_h   = rate_obj.find_srp_adjusters( l_h )
        l_h[:wf_price]  = price_h
        l_h[:wf_adj]    = adj_h
        l_h[:wf_srp]    = srp_h
        #puts "f_15_closed:#{l_h}"
        @f_15_clsd_h[k] = l_h
      end

      @fnma_loans   = MMA::Loan.where("loan_program IN ('#{MMA::FNMA_30_TYPE_ARRAY.join("','")}')").order(:loan_program)
      @fnma_open    = @fnma_loans.select{|loan| ! loan.is_closed }
      @f_30_opn_h   = MMA::Banks::WellsFargo::RegularAdjusters::Adjusters.loan_hash_from_subset( @fnma_open )
      @f_30_opn_h.each do |k, l_h|
        l_h = l_h.stringify_keys
        price_h = rate_obj.find_rate_price( l_h )
        adj_h   = rate_obj.find_price_adjusters( l_h )
        srp_h   = rate_obj.find_srp_adjusters( l_h )
        l_h[:wf_price]  = price_h
        l_h[:wf_adj]    = adj_h
        l_h[:wf_srp]    = srp_h
        #puts "fnma_open:#{l_h}"
        @f_30_opn_h[k] = l_h
      end

      @fnma_closed  = @fnma_loans.select{|loan| loan.is_closed }
      @f_30_clsd_h  = MMA::Banks::WellsFargo::RegularAdjusters::Adjusters.loan_hash_from_subset( @fnma_closed )
      @f_30_clsd_h.each do |k, l_h|
        l_h = l_h.stringify_keys
        price_h = rate_obj.find_rate_price( l_h )
        adj_h   = rate_obj.find_price_adjusters( l_h )
        srp_h   = rate_obj.find_srp_adjusters( l_h )
        l_h[:wf_price]  = price_h
        l_h[:wf_adj]    = adj_h
        l_h[:wf_srp]    = srp_h
        #puts "fnma_closed:#{l_h}"
        @f_30_clsd_h[k] = l_h
      end
    end
  end

  def gnma_type
    if MMA::Loan.count > 0
      @gnma_15_ls = MMA::Loan.where("loan_program IN ('#{MMA::GNMA_15_TYPE_ARRAY.join("','")}')").order(:loan_program)
      @gnma_15_opn  = @gnma_15_ls.select{|loan| ! loan.is_closed }
      @gnma_15_clsd = @gnma_15_ls.select{|loan| loan.is_closed }
      @gnma_loans = MMA::Loan.where("loan_program IN ('#{MMA::GNMA_30_TYPE_ARRAY.join("','")}')").order(:loan_program)
      @gnma_open    = @gnma_loans.select{|loan| ! loan.is_closed }
      @gnma_closed  = @gnma_loans.select{|loan| loan.is_closed }
    end
  end

  def non_conforming_type
    if MMA::Loan.count > 0
      @non_conforming_loans = MMA::Loan.where( "loan_program IN ('#{MMA::NON_CONFORMING_ARR.join("','")}')" ).order(:loan_program)
      @non_conf_open    = @non_conforming_loans.select{|loan| ! loan.is_closed }
      @non_conf_closed  = @non_conforming_loans.select{|loan| loan.is_closed }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excel_file
      file_id = params[:id] || params[:excel_file_id]
      if file_id == 'landing_page'
        @excel_file = ExcelFile.last
      else
        @excel_file = ExcelFile.find( file_id )
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excel_file_params
      params.require( :excel_file ).permit( :xl, :description )
    end
end

app/views/excel_files/_form.html.erb
<%= form_for(@excel_file, :html => {:multipart => true}) do |f| %>
    <% if @excel_file.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@excel_file.errors.count, "error") %> prohibited this excel_file from being saved:</h2>

          <ul>
            <% @excel_file.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :Excel %><br>
      <%= f.file_field :xl %>
    </div>

    <div class="actions">
      <%= f.submit 'Update Excel File' %>
    </div>
<% end %>

app/views/excel_files/edit.html.erb
<h1>Editing Excel File</h1>

<%= render 'form' %>

<%= link_to 'Show', @excel_file %> |
<%= link_to 'Back', excel_files_path %>

app/views/excel_files/fnma_type.html.erb
<style>
  table.output tbody td:nth-child(1){
    width: 110px;
  }
  table.output tbody td:nth-child(2){
    width: 110px;
  }
  table.output tbody td:nth-child(3){
    width: 110px;
  }
  table.output tbody td:nth-child(4){
    width: 130px;
  }
  table.output tbody td:nth-child(5){
    width: 100px;
  }
  table.output tbody td:nth-child(6){
    width: 130px;
    text-align: right;
  }
  table.output tbody td:nth-child(7){
    width: 160px;
    text-align: right;
  }
  table.output tbody td:nth-child(8){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(9){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(10){
    text-align: right;
    width: 100px;
  }
  table.output tbody td:nth-child(11){
    width: 100px;
    text-align: right;
  }
  table.output tbody td.to_right{
    text-align: right;
  }
</style>
<h3>By Mortgage Type</h3>


  <%= render partial: 'excel_files/shared/sub_report_hash', locals: {report_name:'FNMA 5-15 Year', loan_arr: @fnma_15_opn, loan_h: @f_15_opn_h} %>

  <%= render partial: 'excel_files/shared/sub_report_hash', locals: {report_name:'FNMA CLOSED 5-15 Year', loan_arr: @fnma_15_clsd, loan_h: @f_15_clsd_h} %>

  <%= render partial: 'excel_files/shared/sub_report_hash', locals: {report_name:'FNMA 20-30 Year', loan_arr: @fnma_open, loan_h: @f_30_opn_h} %>

  <%= render partial: 'excel_files/shared/sub_report_hash', locals: {report_name:'FNMA CLOSED 20-30 Year', loan_arr: @fnma_closed, loan_h: @f_30_clsd_h} %>

  <%= render partial: 'excel_files/shared/sub_report_total', locals: {xnma_15_opn: @fnma_15_opn, xnma_15_clsd: @fnma_15_clsd, xnma_open: @fnma_open, xnma_closed: @fnma_closed} %>

app/views/excel_files/gnma_type.html.erb
<style>
  table.output tbody td:nth-child(1){
    width: 110px;
  }
  table.output tbody td:nth-child(2){
    width: 110px;
  }
  table.output tbody td:nth-child(3){
    width: 110px;
  }
  table.output tbody td:nth-child(4){
    width: 130px;
  }
  table.output tbody td:nth-child(5){
    width: 100px;
  }
  table.output tbody td:nth-child(6){
    width: 130px;
    text-align: right;
  }
  table.output tbody td:nth-child(7){
    width: 160px;
    text-align: right;
  }
  table.output tbody td:nth-child(8){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(9){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(10){
    text-align: right;
    width: 100px;
  }
  table.output tbody td:nth-child(11){
    width: 100px;
    text-align: right;
  }
  table.output tbody td.to_right{
    text-align: right;
  }
</style>
<h3>By Mortgage Type</h3>


<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'GNMA 5-15 Year', loan_arr: @gnma_15_opn} %>

<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'GNMA CLOSED 5-15 Year', loan_arr: @gnma_15_clsd} %>

<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'GNMA 20-30 Year', loan_arr: @gnma_open} %>

<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'GNMA CLOSED 20-30 Year', loan_arr: @gnma_closed} %>

<%= render partial: 'excel_files/shared/sub_report_total', locals: {xnma_15_opn: @gnma_15_opn, xnma_15_clsd: @gnma_15_clsd, xnma_open: @gnma_open, xnma_closed: @gnma_closed} %>

app/views/excel_files/index.html.erb
<% if user_signed_in? %>

<h1>Listing Excel Files</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Path</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @excel_files.each do |excel_file| %>
      <tr>
        <td><%= excel_file.description %></td>
        <% full_path = excel_file.xl.path %>
        <td><%= full_path.split('/').last if full_path %></td>
        <td><%= link_to 'Show', excel_file %></td>
        <td><%= link_to 'Edit', edit_excel_file_path(excel_file) %></td>
        <td><%= link_to 'Destroy', excel_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Process', "excel_files/#{excel_file.id}/process_file" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excel file', new_excel_file_path %>

<% else %>
    <h3>You currently have no permissions for this page.</h3>
<% end %>

app/views/excel_files/mortgage_type.html.erb
<style>
  table.output tbody td:nth-child(6){
    text-align: right;
  }
  table.output tbody td:nth-child(7){
    text-align: right;
  }
  table.output tbody td:nth-child(8){
    text-align: right;
  }
  table.output tbody td:nth-child(9){
    text-align: right;
  }
  table.output tbody td:nth-child(10){
    text-align: right;
    width: 100px;
  }
  table.output tbody td:nth-child(11){
    text-align: right;
  }
</style>
<h3>By Mortgage Type</h3>
<table class="output">
  <thead>
  <th>L Name</th>
  <th>F Name</th>
  <th>Loan #</th>
  <th>L Program</th>
  <th>Note Rate</th>
  <th>Loan Amt</th>
  <th>Investor #</th>
  <th>Trade Buy</th>
  <th>Trade Sell</th>
  <th>$ Margin</th>
  <th>House Margin</th>
  </thead>
  <tbody>
  <tr>
    <td colspan="11">FNMA 5-15 Year</td>
  </tr>
  <% @fnma_15_ls.each do |loan| %>
      <tr>
        <td><%= loan.borrower_last_name %></td>
        <td><%= loan.borrower_first_name %></td>
        <td><%= loan.loan_num %></td>
        <td><%= loan.loan_program %></td>
        <td><%= loan.note_rate %></td>
        <td><%= number_to_currency( loan.loan_amt ) %></td>
        <td><%= loan.investor %></td>
        <td><%= loan.loan_trade_total_buy_price %></td>
        <td><%= loan.loan_trade_total_sell_price %></td>
        <td><%= number_to_currency( loan.dollar_margin ) %></td>
        <td><%= loan.expected_house_margin %></td>
      </tr>
  <% end %>
  <tr>
    <td colspan="5"></td>
    <td><%= number_to_currency( @fnma_15_ls.sum('loan_amt').to_s )%></td>
  </tr>
  <tr>
    <td colspan="5">FNMA 20-30 Year</td>
    <td></td>
  </tr>
  <% @fnma_loans.each do |loan| %>
      <tr>
        <td><%= loan.borrower_last_name %></td>
        <td><%= loan.borrower_first_name %></td>
        <td><%= loan.loan_num %></td>
        <td><%= loan.loan_program %></td>
        <td><%= loan.note_rate %></td>
        <td><%= number_to_currency( loan.loan_amt ) %></td>
        <td><%= loan.investor %></td>
        <td><%= loan.loan_trade_total_buy_price %></td>
        <td><%= loan.loan_trade_total_sell_price %></td>
        <td><%= number_to_currency( loan.dollar_margin ) %></td>
        <td><%= loan.expected_house_margin %></td>
      </tr>
  <% end %>
  <tr>
    <td colspan="5"></td>
    <td><%= number_to_currency( @fnma_loans.sum('loan_amt').to_s )%></td>
  </tr>
  <tr>
    <td colspan="5"></td>
  </tr>
  </tbody>
</table>

app/views/excel_files/new.html.erb
<h1>New Excel File</h1>

<%= render 'form' %>

<%= link_to 'Excel Files', excel_files_path %>&nbsp;&nbsp;&nbsp;
<%= link_to 'Home Page', root_path %>

app/views/excel_files/non_conforming_type.html.erb
<style>
  table.output tbody td:nth-child(1){
    width: 110px;
  }
  table.output tbody td:nth-child(2){
    width: 110px;
  }
  table.output tbody td:nth-child(3){
    width: 110px;
  }
  table.output tbody td:nth-child(4){
    width: 130px;
  }
  table.output tbody td:nth-child(5){
    width: 100px;
  }
  table.output tbody td:nth-child(6){
    width: 130px;
    text-align: right;
  }
  table.output tbody td:nth-child(7){
    width: 160px;
    text-align: right;
  }
  table.output tbody td:nth-child(8){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(9){
    width: 100px;
    text-align: right;
  }
  table.output tbody td:nth-child(10){
    text-align: right;
    width: 100px;
  }
  table.output tbody td:nth-child(11){
    width: 100px;
    text-align: right;
  }
  table.output tbody td.to_right{
    text-align: right;
  }
</style>
<h3>By Mortgage Type</h3>


<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'Non Conforming Loans', loan_arr: @non_conf_open} %>

<%= render partial: 'excel_files/shared/sub_report', locals: {report_name:'CLOSED Non Conforming Loans', loan_arr: @non_conf_closed} %>


<%= render partial: 'excel_files/shared/sub_report_total', locals: {xnma_15_opn: [], xnma_15_clsd: [], xnma_open: @non_conf_open, xnma_closed: @non_conf_closed} %>

app/views/excel_files/process_file.html.erb
<div class="btn btn-lg"><%= link_to('Full Pipeline', excel_file_total_pipeline_path) %></div>

<div class="btn btn-lg"><%= link_to('FNMA Mortgages', excel_file_fnma_type_path) %></div>

<div class="btn btn-lg"><%= link_to('GNMA Mortgages', excel_file_gnma_type_path) %></div>

<div class="btn btn-lg"><%= link_to('Non Conforming Mortgages', excel_file_non_conforming_type_path) %></div>

app/views/excel_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File Description:</strong>
  <%= @excel_file.description %>
</p>

<p>
  <strong>Excel File:</strong>
  <%= @excel_file.xl %>
</p>

<%= link_to 'Edit', edit_excel_file_path(@excel_file) %> |
<%= link_to 'Back', excel_files_path %>

app/views/excel_files/total_pipeline.html.erb
<style>
  table.output tbody td:nth-child(2){
    text-align: right;
  }
</style>
<h3>Total Pipeline</h3>

<table>
  <thead>
  <!--<th>L Name</th>-->
  <!--<th>F Name</th>-->
  <th>Loan #</th>
  <th>L Program</th>
  <th>Note Rate</th>
  <th>Loan Amt</th>
  <th>Investor #</th>
  <th>Trade Buy</th>
  <th>Trade Sell</th>
  <th>$ Margin</th>
  <th>House Margin</th>
  </thead>
  <tbody>
  <% MMA::Loan.all.each do |loan| %>
      <tr>
        <!--<td><%# loan.borrower_last_name %></td>-->
        <!--<td><%# loan.borrower_first_name %></td>-->
        <td><%= loan.loan_num %></td>
        <td><%= loan.loan_program %></td>
        <td><%= loan.note_rate %></td>
        <td><%= loan.loan_amt %></td>
        <td><%= loan.investor %></td>
        <td><%= loan.loan_trade_total_buy_price %></td>
        <td><%= loan.loan_trade_total_sell_price %></td>
        <td><%= loan.dollar_margin %></td>
        <td><%= loan.expected_house_margin %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% ttl = 0; MMA::Loan.select{|x| ttl = ttl + x.dollar_margin} %>
<% ttl2 = ( ttl.to_f / MMA::Loan.sum('loan_amt').to_f ) * 100 %>
<table class="output">
  <thead>
  <tr>
    <th>Name</th>
    <th>Amount</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Total Pipleine</td>
    <td><%= number_to_currency( MMA::Loan.sum('loan_amt').to_s ) %></td>
  </tr>
  <tr>
    <td>Aggregate Dollar Margin</td>
    <td><%= ttl.round(2).to_s %></td>
  </tr>
  <tr>
    <td>Avg House Margin</td>
    <td><%= ttl2.round(5).to_s %>%</td>
  </tr>
  </tbody>
</table>