config/routes.rb
Rails.application.routes.draw do
  resources :wells_fargo_srp_sheets
  resources :wells_fargo_price_sheets
  devise_for :users

  resources :excel_files do
    get 'process_file'
    get 'total_pipeline'
    get 'fnma_type'
    get 'gnma_type'
    get 'non_conforming_type'
  end

  root 'welcome#index'

end

app/models/wells_fargo_srp_sheet.rb
class WellsFargoSrpSheet < ActiveRecord::Base
  attr_accessor :thefile, :name #:description
  mount_uploader :thefile, WellsFargoSrpUploader
  serialize :json

  def filename
    @srp.split('/').last unless @srp.nil?
  end
end

app/controllers/wells_fargo_srp_sheets_controller.rb
class WellsFargoSrpSheetsController < ApplicationController
  before_action :set_wells_fargo_srp_sheet, only: [:show, :edit, :update, :destroy]

  # GET /wells_fargo_srp_sheets
  # GET /wells_fargo_srp_sheets.json
  def index
    puts 'within wells_fargo_srp_sheets_controller index method'
    @wells_fargo_srp_sheets = WellsFargoSrpSheet.all
  end

  # GET /wells_fargo_srp_sheets/1
  # GET /wells_fargo_srp_sheets/1.json
  def show
  end

  # GET /wells_fargo_srp_sheets/new
  def new
    puts 'within wells_fargo_srp_sheets_controller new method'
    @wells_fargo_srp_sheet = WellsFargoSrpSheet.new
  end

  # GET /wells_fargo_srp_sheets/1/edit
  def edit
  end

  # POST /wells_fargo_srp_sheets
  # POST /wells_fargo_srp_sheets.json
  def create
    puts "within create method of wells_fargo_srp_sheets with params: #{wells_fargo_srp_sheet_params.inspect}"
    @wells_fargo_srp_sheet = WellsFargoSrpSheet.new(wells_fargo_srp_sheet_params)

    respond_to do |format|
      puts "the format is:#{format}"
      puts 'about to save'
      begin
        if @wells_fargo_srp_sheet.save
          format.html { redirect_to @wells_fargo_srp_sheet, notice: 'Wells fargo srp sheet was successfully created.' }
          format.json { render :show, status: :created, location: @wells_fargo_srp_sheet }
        else
          format.html { render :new }
          format.json { render json: @wells_fargo_srp_sheet.errors, status: :unprocessable_entity }
        end
      rescue Exception=>ex
        puts "Exception in create controller method:#{ex.message}"
        puts ex.backtrace
      end
    end
  end

  # PATCH/PUT /wells_fargo_srp_sheets/1
  # PATCH/PUT /wells_fargo_srp_sheets/1.json
  def update
    Rails.logger.info "within update method of wells_fargo_srp_sheet with params:#{wells_fargo_srp_sheet_params.inspect}"
    respond_to do |format|
      puts "the format is:#{format}"
      puts 'about to update'
      begin
        if @wells_fargo_srp_sheet.update(wells_fargo_srp_sheet_params)
          format.html { redirect_to @wells_fargo_srp_sheet, notice: 'Wells fargo srp sheet was successfully updated.' }
          format.json { render :show, status: :ok, location: @wells_fargo_srp_sheet }
        else
          format.html { render :edit }
          format.json { render json: @wells_fargo_srp_sheet.errors, status: :unprocessable_entity }
        end
      rescue Exception=>ex
        puts "Exception in update controller method:#{ex.message}"
        puts ex.backtrace
      end
    end
  end

  # DELETE /wells_fargo_srp_sheets/1
  # DELETE /wells_fargo_srp_sheets/1.json
  def destroy
    puts 'about to destroy the worksheet'
    @wells_fargo_srp_sheet.destroy
    respond_to do |format|
      format.html { redirect_to wells_fargo_srp_sheets_url, notice: 'Wells Fargo srp sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wells_fargo_srp_sheet
      @wells_fargo_srp_sheet = WellsFargoSrpSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wells_fargo_srp_sheet_params
      params.require(:wells_fargo_srp_sheet).permit(:description, :thefile)
    end
end

app/helpers/wells_fargo_srp_sheets_helper.rb
module WellsFargoSrpSheetsHelper
end

app/views/wells_fargo_srp_sheets/_form.html.erb
<%= form_for(@wells_fargo_srp_sheet, :html => {:multipart => true}) do |f| %>
  <% if @wells_fargo_srp_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wells_fargo_srp_sheet.errors.count, "error") %> prohibited this wells_fargo_srp_sheet from being saved:</h2>

      <ul>
      <% @wells_fargo_srp_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>&nbsp;
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label 'SRP File' %><br/>&nbsp;
    <%= f.file_field :thefile %><br/>
    <%# f.text_field :srp, :maxlength=>'254', :readonly => true %>
  </div>
    <div class="actions">
      <% if @wells_fargo_srp_sheet.nil? || @wells_fargo_srp_sheet.thefile.path.blank? %>
          <%= f.submit 'Upload SRP File' %>
      <% else %>
          <%= f.submit 'Update SRP File' %>
      <% end %>
    </div>
<% end %>

app/views/wells_fargo_srp_sheets/edit.html.erb
<h1>Editing Wells Fargo Srp Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @wells_fargo_srp_sheet %> |
<%= link_to 'Back', wells_fargo_srp_sheets_path %>

app/views/wells_fargo_srp_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wells Fargo SRP Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>File Name</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @wells_fargo_srp_sheets.each do |wells_fargo_srp_sheet| %>
      <tr>
        <td><%= wells_fargo_srp_sheet.description %></td>
        <% full_path = wells_fargo_srp_sheet.thefile ? wells_fargo_srp_sheet.thefile.path : ''%>
        <td><%= full_path.split('/').last if full_path %></td>
        <td><%= link_to 'Show', wells_fargo_srp_sheet %></td>
        <td><%= link_to 'Edit', edit_wells_fargo_srp_sheet_path(wells_fargo_srp_sheet) %></td>
        <td><%= link_to 'Destroy', wells_fargo_srp_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wells Fargo SRP Sheet', new_wells_fargo_srp_sheet_path %>

app/views/wells_fargo_srp_sheets/new.html.erb
<h1>New Wells Fargo Srp Sheet</h1>

<%= render 'form' %>

<%= link_to 'SRP Sheets', wells_fargo_srp_sheets_path %>&nbsp;&nbsp;&nbsp;
<%= link_to 'Home Page', root_path %>

app/views/wells_fargo_srp_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @wells_fargo_srp_sheet.description %>
</p>

<p>
  <strong>SRP File:</strong>
  <%= @wells_fargo_srp_sheet.thefile %>
</p>

<%= link_to 'Edit', edit_wells_fargo_srp_sheet_path(@wells_fargo_srp_sheet) %> |
<%= link_to 'Back', wells_fargo_srp_sheets_path %>