config/routes.rb
Rails.application.routes.draw do
  resources :wells_fargo_srp_sheets
  resources :wells_fargo_price_sheets
  devise_for :users

  resources :excel_files do
    get 'process_file'
    get 'total_pipeline'
    get 'fnma_type'
    get 'gnma_type'
    get 'non_conforming_type'
  end

  root 'welcome#index'

end

app/controllers/wells_fargo_price_sheets_controller.rb
class WellsFargoPriceSheetsController < ApplicationController
  before_action :set_wells_fargo_price_sheet, only: [:show, :edit, :update, :destroy]

  # GET /wells_fargo_price_sheets
  # GET /wells_fargo_price_sheets.json
  def index
    puts 'in wells_fargo_price_sheets controller index method'
    begin
      @wells_fargo_price_sheets = WellsFargoPriceSheet.all
    rescue Exception=>ex
      puts "Exception in wf price sheets index controller #{ex.message}"
      puts ex.backtrace
    end
  end

  # GET /wells_fargo_price_sheets/1
  # GET /wells_fargo_price_sheets/1.json
  def show
    @wells_fargo_price_sheet = WellsFargoPriceSheet.find(params['id'] )
  end

  # GET /wells_fargo_price_sheets/new
  def new
    puts 'in wells_fargo_price_sheets controller new method'
    @wells_fargo_price_sheet = WellsFargoPriceSheet.new
  end

  # GET /wells_fargo_price_sheets/1/edit
  def edit
  end

  # POST /wells_fargo_price_sheets
  # POST /wells_fargo_price_sheets.json
  def create
    puts 'in WF Price Sheet create'
    puts "the params are:#{wells_fargo_price_sheet_params}"
    @wells_fargo_price_sheet = WellsFargoPriceSheet.new(wells_fargo_price_sheet_params)

    respond_to do |format|
      if @wells_fargo_price_sheet.save
        format.html { redirect_to @wells_fargo_price_sheet, notice: 'Wells fargo price sheet was successfully created.' }
        format.json { render :show, status: :created, location: @wells_fargo_price_sheet }
      else
        format.html { render :new }
        format.json { render json: @wells_fargo_price_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wells_fargo_price_sheets/1
  # PATCH/PUT /wells_fargo_price_sheets/1.json
  def update
    puts 'in WF Price Sheet update'
    puts "the params are:#{wells_fargo_price_sheet_params}"
    respond_to do |format|
      if @wells_fargo_price_sheet.update(wells_fargo_price_sheet_params)
        format.html { redirect_to @wells_fargo_price_sheet, notice: 'Wells fargo price sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @wells_fargo_price_sheet }
      else
        format.html { render :edit }
        format.json { render json: @wells_fargo_price_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wells_fargo_price_sheets/1
  # DELETE /wells_fargo_price_sheets/1.json
  def destroy
    puts 'about to destroy the price sheet'
    @wells_fargo_price_sheet.destroy
    respond_to do |format|
      format.html { redirect_to wells_fargo_price_sheets_url, notice: 'Wells Fargo price sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wells_fargo_price_sheet
      @wells_fargo_price_sheet = WellsFargoPriceSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wells_fargo_price_sheet_params
      params.require(:wells_fargo_price_sheet).permit(:description, :thefile)
    end
end

app/helpers/wells_fargo_price_sheets_helper.rb
module WellsFargoPriceSheetsHelper
end

app/views/wells_fargo_price_sheets/_form.html.erb
<%= form_for(@wells_fargo_price_sheet, :html => {:multipart => true}) do |f| %>
  <% if @wells_fargo_price_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wells_fargo_price_sheet.errors.count, "error") %> prohibited this wells_fargo_price_sheet from being saved:</h2>

      <ul>
      <% @wells_fargo_price_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label 'Price Workbook' %>
    <%= f.file_field :thefile %><br/>
      <%# f.text_field :thefile, :maxlength=>'254', :readonly => true %>
  </div>
  <div class="actions">
    <% if @wells_fargo_price_sheet.nil? || @wells_fargo_price_sheet.thefile.blank? %>
        <%= f.submit 'Upload Price Workbook' %>
    <% else %>
        <%= f.submit 'Update Price Workbook' %>
    <% end %>
  </div>
<% end %>

app/views/wells_fargo_price_sheets/edit.html.erb
<h1>Editing Wells Fargo Price Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @wells_fargo_price_sheet %> |
<%= link_to 'Back', wells_fargo_price_sheets_path %>

app/views/wells_fargo_price_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wells Fargo Price Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>&nbsp;Price Sheet&nbsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wells_fargo_price_sheets.each do |wells_fargo_price_sheet| %>
      <tr>
        <td><%= wells_fargo_price_sheet.description %></td>
        <% full_path = wells_fargo_price_sheet.thefile.path %>
        <td><%= full_path.to_s.split('/').last if full_path %></td>
        <td><%= link_to 'Show', wells_fargo_price_sheet %></td>
        <td><%= link_to 'Edit', edit_wells_fargo_price_sheet_path(wells_fargo_price_sheet) %></td>
        <td><%= link_to 'Destroy', wells_fargo_price_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wells fargo price sheet', new_wells_fargo_price_sheet_path %>

app/views/wells_fargo_price_sheets/new.html.erb
<h1>New Wells Fargo Price Sheet</h1>

<%= render 'form' %>

<%= link_to 'Price Sheets', wells_fargo_price_sheets_path %>&nbsp;&nbsp;&nbsp;
<%= link_to 'Home Page', root_path %>

app/views/wells_fargo_price_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @wells_fargo_price_sheet.description %>
</p>

<p>
  <strong>Price File:</strong>
  <%= @wells_fargo_price_sheet.thefile %>
</p>

<%= link_to 'Edit', edit_wells_fargo_price_sheet_path(@wells_fargo_price_sheet) %> |
<%= link_to 'Back', wells_fargo_price_sheets_path %>